apiVersion: v1
kind: Service
metadata:
  name: yellowjobs-backend
spec:
  selector:
    app: yellowjobs-backend
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
      nodePort: 30446 # (30000-32767 valid)
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yellowjobs-backend
spec:
  selector:
    matchLabels:
      app: yellowjobs-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: yellowjobs-backend
    spec:
      containers:
        - name: yellowjobs-backend
          image: docker.io/ans29hul/yellowjobs-backend:latest
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: yellowjobs-backend-mongo-uri
                  key: node_backend
            - name: BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: b-token
                  key: b-token
          ports:
            - containerPort: 5000
              protocol: "TCP"
